### ISSUE TITLE
zmqaudio core dumps

### ISSUE THREAD

**Issue by breaker-of-stone** [noisebin/controller#6]
FAO @professionalmoment

zmqaudio crashes through a core dump in about 50% of runs with a variety of messages, immediately after we select a device number, i.e.:

```
zmqaudio: malloc.c:4302: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.

Segmentation fault (core dumped)

malloc(): invalid size (unsorted)
Aborted (core dumped)

zmqaudio: malloc.c:4302: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
Aborted (core dumped)
```
A core dump seems to occur 100% of the time if we select the 'Built-in Audio Stereo' device.

We have zmqaudio running on a Raspberry Pi 4 with a WAVLink 4 port USB hub + 2 mini audio adapters.
The only other attachment on the Pi is a USB/ Ethernet adapter.
OS is ubuntu 22.04 workstation (pipewire built-in).

We have successfully played test samples from the Python client through zmqaudio, on both min audio adapters plus the on-board audio.

We have not attempted binding the channels into a composite device yet.

Detection of the mini audio adapters sometimes fails, but can be achieved by disconnect/reconnect of the USB hub.  Dis/re-connect of the audio adapter itself is insufficient.

zmqaudio was built by:

```
gcc -Wall zmqaudio.c -o zmqaudio -lczmq -lzmq -ldl -lpthread -lm -lcjson -O2
```
Libraries are freshly built from source repos, with exception of libzmq which was built from the 4.3.4 release in DRAFT mode, due to our use of the experimental SERVER socket type.

libczmq may therefore incorporate this slightly older library, as we built but did did not install a fresh libzmq.so.5.2.5.

ls -l /usr/local/lib
total 69408
drwxr-xr-x 3 root root     4096 Jan  5 20:16 cmake
lrwxrwxrwx 1 root root       13 Jan  5 20:16 libcjson.so -> libcjson.so.1
lrwxrwxrwx 1 root root       18 Jan  5 20:16 libcjson.so.1 -> libcjson.so.1.7.15
-rw-r--r-- 1 root root    47096 Jan  5 20:15 libcjson.so.1.7.15
-rw-r--r-- 1 root root  4635348 Jan  1 21:09 libczmq.a
-rwxr-xr-x 1 root root     1011 Jan  1 21:09 libczmq.la
lrwxrwxrwx 1 root root       16 Jan  1 21:09 libczmq.so -> libczmq.so.4.2.2
lrwxrwxrwx 1 root root       16 Jan  1 21:09 libczmq.so.4 -> libczmq.so.4.2.2
-rwxr-xr-x 1 root root  1964512 Jan  1 21:09 libczmq.so.4.2.2
-rw-r--r-- 1 root root  2124360 Jan  1 21:01 libsodium.a
-rwxr-xr-x 1 root root      943 Jan  1 21:01 libsodium.la
lrwxrwxrwx 1 root root       19 Jan  1 21:01 libsodium.so -> libsodium.so.23.2.0
lrwxrwxrwx 1 root root       19 Jan  1 21:01 libsodium.so.23 -> libsodium.so.23.2.0
-rwxr-xr-x 1 root root  1076320 Jan  1 21:01 libsodium.so.23.2.0
-rw-r--r-- 1 root root 46203312 Oct  2 20:25 libzmq.a
-rwxr-xr-x 1 root root      940 Oct  2 20:24 libzmq.la
lrwxrwxrwx 1 root root       15 Oct  2 20:24 libzmq.so -> libzmq.so.5.2.4
lrwxrwxrwx 1 root root       15 Oct  2 20:24 libzmq.so.5 -> libzmq.so.5.2.4
-rwxr-xr-x 1 root root 14467304 Oct  2 20:24 libzmq.so.5.2.4
```

```
pw-link --version
pw-link
Compiled with libpipewire 0.3.55
Linked with libpipewire 0.3.55
```

```
pactl --version
pactl 15.99.1
Compiled with libpulse 15.99.0
Linked with libpulse 15.99.0
```
--- END ---

**Comment by professionalmoment** [comment]
I *think* I reproduced the issue on an x86 ubuntu vm (haven't tested on an emulated arm system).
ubuntu 20.04 ships with pipewire-media-session by default (which is depreciated) after switching over to wireplumber the problem seemed to go away.  I also noticed despite shipping with pipewire it doesn't seem to be taking care of pulseaudio calls. You can swap over to the configuration I got to work with:

`sudo apt purge pipewire-media-session`
`sudo apt install wireplumber pipewire-pulse`
`systemctl --user enable --now wireplumber pipewire-pulse`

**Comment by professionalmoment** [comment]
you may have to reboot for systemd to get rid of the pipewire-media-session service as it is masked in a weird way that I couldn't just disable

**Comment by breaker-of-stone** [comment]
Swapping in wireplumber sorted this issue - spot on @professionalmoment!
Closing ...
